global using System.IdentityModel.Tokens.Jwt;
global using System.Security.Claims;
global using System.Text;
global using System.Text.Json;
global using System.Threading.RateLimiting;
global using Box.Extensions;
global using Box.Entities;
global using Box.Response;
global using Box.Routes;
global using Box.Utils;
global using Microsoft.AspNetCore.Authentication.JwtBearer;
global using Microsoft.AspNetCore.RateLimiting;
global using Microsoft.IdentityModel.Tokens;
global using Microsoft.OpenApi.Models;
using Box.Http;
using Box.Middlewares;
using Polly;